### ISSUE TITLE
Question: URL support?

### ISSUE THREAD

**Issue by RhomGit** [HiraokaHyperTools/PDFsharp#17]
Hi,

I am using the XpsConverter which is great however I would like to have URL links to files/web pages (local file system and remote). Is this possible?

**Comment by kenjiuno** [comment]
Hi.

Does it mean you want to invoke `PdfSharp.Xps.XpsConverter.Convert` with URL like the following one?
https://github.com/HiraokaHyperTools/PDFsharp/raw/master/PDFsharp/testing/PdfSharp.Xps.UnitTests/Render2/xps/bulletMarks.xps

**Comment by RhomGit** [comment]
I was hoping for hyperlink support, similar to what is discussed here:
https://sudonull.com/post/119046-WPF-PDF-via-PDFSharpXps-repair-the-output-of-hyperlinks

**Comment by kenjiuno** [comment]
Hi, thanks for information! I understood about the URL links.
It will take longer because I need to recall PDFsharp's detail and learn about Hyperlink.

📝
- https://docs.microsoft.com/dotnet/api/system.windows.documents.hyperlink?view=netcore-3.1
- https://www.c-sharpcorner.com/UploadFile/mahesh/hyperlink-in-wpf/

**Comment by RhomGit** [comment]
Thank you for an amazing turnaround, I have tested this and it works perfectly!

**Comment by kenjiuno** [comment]
Hi, thanks for catching up the update!
I have published updates to nuget and they are available now.

kenjiuno.PdfSharp-WPF 1.31.5673
kenjiuno.PdfSharp.Xps 1.1.7
